### ISSUE TITLE
default.config rework

### ISSUE THREAD

**Issue by jensdrenhaus** [system-transparency/system-transparency#105]
According to the updated / reordered `default.config` take a look at the following section:
```
# ST_KERNEL_VERSION_XX defines the linux kernel version of the LinuxBoot
# distribution for the appropriate installation option.
#
ST_KERNEL_VERSION=5.10.21
#ST_MBR_BOOTLOADER_KERNEL_VERSION=
#ST_EFI_APPLICATION_EFISTUB_KERNEL_VERSION=

# ST_XX_KERNEL_CONFIG is the linux kernel defconfig loaded before
# the kernel is beeing built for the appropiate installation option.
#
ST_MBR_BOOTLOADER_KERNEL_CONFIG="contrib/boards/${BOARD}/mbr_linuxboot.defconfig"
ST_EFI_APPLICATION_EFISTUB_KERNEL_CONFIG="contrib/boards/${BOARD}/efi_linuxboot.defconfig"
```
I wonder if we need `ST_KERNEL_VERSION` as a general fallback at all? Why not just go with the dedicated ones for each installation option (both set to 5.10.21)?
In this case I suggest renaming them into `ST_KERNEL_VERSION_MBR_BOOTLOADER_INSTALLATION` and `ST_KERNEL_VERSION_EFI_APPLICATION_INSTALLATION` respectively.

And accordingly:
`ST_MBR_BOOTLOADER_KERNEL_CONFIG` → `ST_KERNEL_CONFIG_MBR_BOOTLOADER_INSTALLATION`
`ST_EFI_APPLICATION_EFISTUB_KERNEL_CONFIG` → `ST_KERNEL_CONFIG_EFI_APPLICATION_INSTALLATION`

I don't want to just edit this in the `default.config` since this has impact on the make ecosystem.

**Comment by sylv-io** [comment]
In my opinon we should compile a single kernel, since both use the same defconfig (exept from efi_strub support, which can be enabled on both kernels)

**Comment by sylv-io** [comment]
Issue obsolete since we now only compile a single kernel.
