### ISSUE TITLE
security_configuration.json generation is incorrect

### ISSUE THREAD

**Issue by bjoto** [system-transparency/system-transparency#134]
When using the `ST_NUM_SIGNATURES` config option in st.config an incorrect `security_configuration.json` file is produced.

The generated json contains `"minimal_signatures_match"` instead of the correct `"min_valid_sigs_required"`.

The following patch resolves the issue:
```
diff --git a/scripts/security_config.sh b/scripts/security_config.sh
index 45bfdddaaf2d..cb93efb197b7 100755
--- a/scripts/security_config.sh
+++ b/scripts/security_config.sh
@@ -44,7 +44,7 @@ use_ospkg_cache=${ST_USE_PKG_CACHE}
 cat >"${output}" <<EOL
 {
   "version":${version},
-  "minimal_signatures_match": ${num_signatures},
+  "min_valid_sigs_required": ${num_signatures},
   "boot_mode": "${boot_mode}",
   "use_ospkg_cache": ${use_ospkg_cache}
 }
```
Note that the README.md needs to be updated in the example `security_configuration.json`.

**Comment by sylv-io** [comment]
Hi @bjoto,

you're right. Looks like this config was renamed in https://github.com/system-transparency/stboot/commit/7514d930cf23cd4a3eabe81d30285aa560ab0b81 without adapting it here.
Moving to stricter parsing sound good to me :+1:

**Comment by bjoto** [comment]
I've submitted a PR that resolves this issue: https://github.com/system-transparency/system-transparency/pull/137
