### ISSUE TITLE
Generate ISO, in addition to regular IMG

### ISSUE THREAD

**Issue by bjoto** [system-transparency/system-transparency#141]
When stboot gains support diskless configurations, or configuration with just one STBOOT partition, support for generating ISO images should be added.

A lot of LOM implementations only support ISO, and not IMG.

An example how one can generate an EFI bootable ISO:
```
#!/bin/bash

. .envrc
task image-efi
mkdir iso
cp out/artifacts/efi_boot_partition.vfat iso/efi.img
xorriso -as mkisofs -R -f -V STBOOT -e efi.img -no-emul-boot -o stboot.iso iso
```

**Comment by sylv-io** [comment]
#144 adds support to build ISO images

**Comment by jensdrenhaus** [comment]
Done in #144
