### ISSUE TITLE
Consider caching large artifacts for the CI setup

### ISSUE THREAD

**Issue by MDr164** [system-transparency/system-transparency#163]
Currently the CI runs are taking quite some time because each runs downloads Ubuntu images that are fairly large. It might speed up CI runs and reduce resource costs in GitHub actions to implement a cache like this: https://github.com/actions/cache
In addition things like Go modules could also be cached that way, potentially reducing CI run time even further.

**Comment by jensdrenhaus** [comment]
Further development on https://git.glasklar.is/system-transparency/core/system-transparency
