### ISSUE TITLE
Cannot set filepath for "cdrom:" based host-config

### ISSUE THREAD

**Issue by bjoto** [system-transparency/system-transparency#165]
The new way of setting host-config variables does not support setting the path for cdrom: paths:
E.g
```
       ST_HOST_CONFIG_FILE= cdrom
       ST_HOST_CONFIG_LOCATION=path
```

Will always set the path to `-host-config cdrom:host_configuration.json` instead of cdrom:path.

**Comment by sylv-io** [comment]
So currently we have two configs:

`ST_HOST_CONFIG_LOCATION` to set the way how the host configuration is stored (e.g initramfs, cdrom, efivar...)
`ST_HOST_CONFIG_FILE` to define a local file inside the build environment, which will be copied into the installation image.

Currently, we do not have a way to define where to store the file inside the image, so it is using predefined path like `host_configuration.json` inside cdrom.

Should we define another config to define the path inside the image, implement it analog to stboot? (e.g. ST_HOST_CONFIG_LOCATION="cdrom:/path/to/host_configuration.json")

**Comment by bjoto** [comment]
We discussed this on slack:
```
[sylv](https://app.slack.com/team/U01RB2AMU3G):tinmole:  [4:46 PM](https://mullvad.slack.com/archives/D01SH2TJ8KT/p1646927176447039)
sure :+1: i'm only thinking about what is the best way to reflect this in the st.config file. Should we make it similar to the stboot flag argument or add another config only for the initramfs and cdrom path.

[bjorntopel](https://app.slack.com/team/U01KVQRTB6E)  [4:46 PM](https://mullvad.slack.com/archives/D01SH2TJ8KT/p1646927215495729)
Maybe change to STBOOT_HOSTCONFIG_EFIVAR to "something PATH" and use for all?
[4:47](https://mullvad.slack.com/archives/D01SH2TJ8KT/p1646927226197659)
And if initramfs, do a copy?

[sylv](https://app.slack.com/team/U01RB2AMU3G):tinmole:  [4:47 PM](https://mullvad.slack.com/archives/D01SH2TJ8KT/p1646927261750549)
yeah, I was thinking about this option too. sgtm
```

**Comment by sylv-io** [comment]
So I renamed `ST_HOST_CONFIG_LOCATION` to `ST_HOST_CONFIG_MODE` to define how the config is stored.
`HOST_CONFIG_LOCATION` defines the path or efivar name depending on the selected mode.

Does that sound like what you imagined?

see: 302c21dd6a6dba6682a5ec18973468c5eddc2c7b

**Comment by sylv-io** [comment]
#168
