### ISSUE TITLE
Unable to go install u_root

### ISSUE THREAD

**Issue by ln5** [system-transparency/system-transparency#19]
system-transparency$ bash -x $(pwd)/stboot/install_u-root.sh
    + set -o errexit
    + set -o pipefail
    + set -o nounset
    + failed='\e[1;5;31mfailed\e[0m'
    ++ go env GOPATH
    + gopath=/home/debian/go
    + '[' -z /home/debian/go ']'
    + uroot_src=/home/debian/go/src/github.com/u-root/u-root
    + branch=stboot
    + choose_branch=false
    + getopts bu opt
    + echo '[INFO]: unsing GOPATH /home/debian/go'
    [INFO]: unsing GOPATH /home/debian/go
    + '[' '!' -d /home/debian/go/src/github.com/u-root/u-root ']'
    + echo '[INFO]: using repository /home/debian/go/src/github.com/u-root/u-root'
    [INFO]: using repository /home/debian/go/src/github.com/u-root/u-root
    + cd /home/debian/go/src/github.com/u-root/u-root
    + false
    + echo '[INFO]: switch to branch stboot'
    [INFO]: switch to branch stboot
    + git checkout --quiet stboot
    + git status
    On branch stboot
    Your branch is up to date with 'origin/stboot'.
    
    nothing to commit, working tree clean
    + echo '[INFO]: install u-root'
    [INFO]: install u-root
    + GOPATH=/home/debian/go
    + go install /home/debian/go/src/github.com/u-root/u-root/
    + echo '[INFO]: install u-root stboot patch'
    [INFO]: install u-root stboot patch
    + GOPATH=/home/debian/go
    + go install /home/debian/go/src/github.com/u-root/u-root/cmds/boot/stboot
    pkg/dhclient/dhclient.go:23:2: build constraints exclude all Go files in /home/debian/go/src/github.com/u-root/u-root/vendor/github.com/insomniacslk/dhcp/dhcpv4/nclient4
    + echo -e 'installing u-root stboot patch \e[1;5;31mfailed\e[0m'
    installing u-root stboot patch failed
    + exit 1

**Comment by jensdrenhaus** [comment]
There are still problems with GOMODULES I think.
Try to turn GO111MODULES of with `go env -w GO111MODULE=off`
This is my current setting with go1.13.3 linux/amd64

**Comment by ln5** [comment]
debian@buster:/usr/src/system-transparency$ go env -w GO111MODULE=off
    flag provided but not defined: -w
    usage: go env [-json] [var ...]

Debian Buster is on 1.11.6: 

    debian@buster:/usr/src/system-transparency$ go version
    go version go1.11.6 linux/amd64

Is there any chance that 1.11 will do, or should I try to get to at least 1.13.3?

**Comment by ln5** [comment]
> Is there any chance that 1.11 will do, or should I try to get to at least 1.13.3?

u-root/README.md has

    Make sure your Go version is 1.12. Make sure your `GOPATH` is set up correctly.

so I think I know what I have to do.
Adding a note to system-transparency/README.md about it and closing.
Thanks!
