### ISSUE TITLE
simplify build_kernel.sh

### ISSUE THREAD

**Issue by Sickeroni** [system-transparency/system-transparency#53]
./stboot-installation/common/build_kernel.sh is using 3 parameters
first one is a defconfigfile. 
the script checks if a file exists with $NAME.patch. If it existst it uses it

to improve readability we should remove this checks and just use the patch(ed) file.

**Comment by jensdrenhaus** [comment]
I think, the pathed file is not present in all situations

**Comment by jensdrenhaus** [comment]
Building the linuxboot kernel is now done by make.
