### ISSUE TITLE
Insecure /tmp usage (use mktemp instead)

### ISSUE THREAD

**Issue by emanuelb** [system-transparency/system-transparency#59]
Files / Folders are used in /tmp with static or predictable names, thus vulnerable to malicious usage from other users, for example:
https://github.com/system-transparency/system-transparency/blob/261a408e20dd0a4bb044513c3b0e82d3232cb165/scripts/start_qemu_mbr_bootloader.sh#L18-L24
another user can create /tmp/mytpm$i with 777 permissions that will be used by the running script (need to win the race condition of TOCTOU check, so it will set i to non existent directory, while it will be created before the mkdir command)
use `mktemp` or `mktemp -d` to create files/folders instead.
There are other scripts in this repo which are probably impacted as well (even in Dockerfile where there is mostly no impact it's better to always follow this best-practice of secure usage with temporary files)
another example is: (usage of static `/tmp/rootcert` path)
https://github.com/system-transparency/system-transparency/blob/495588e0349c0bba04d66fff02b42b419e26759a/scripts/make_keys_and_certs.sh#L28-L30

**Comment by sylv-io** [comment]
Fixed in #77 :+1:
