### ISSUE TITLE
Use --no-install-recommends for apt-get install commands

### ISSUE THREAD

**Issue by emanuelb** [system-transparency/system-transparency#60]
adding `--no-install-recommends` for `apt-get install` commands will reduce the amount of packages installed (then the package list may need to be increased with some required dependencies for the usage which are part of the recommended list)
https://github.com/system-transparency/system-transparency/blob/c88c2fe59ecc334c5bbd96b89c94500b455f1a0e/operating-system/ubuntu/Dockerfile#L17
https://github.com/system-transparency/system-transparency/blob/c88c2fe59ecc334c5bbd96b89c94500b455f1a0e/operating-system/debian/Dockerfile#L14
https://github.com/system-transparency/system-transparency/blob/fc27b576b6e9fe42f9faeb9c0bb2d1e9264fc855/stboot-installation/coreboot-payload/README.md#L10

**Comment by sylv-io** [comment]
Obsolete, since OS packages will not be build in this repo anymore. (except of demo:ospkg)
Dockerfile was removed
