### ISSUE TITLE
Use /bin/sh instead of /bin/bash when possible

### ISSUE THREAD

**Issue by emanuelb** [system-transparency/system-transparency#61]
The scripts in this repo are using `#!/bin/bash`, for some of them it's possible to use `#!/bin/sh` instead without modifications:
https://github.com/system-transparency/system-transparency/blob/master/operating-system/ubuntu/debos_enable_ssh.sh
 https://github.com/system-transparency/system-transparency/blob/master/operating-system/ubuntu/debos_cleanup_some_irreproducible_data.sh
it might worth to change it for some other scripts if they not relaying to much on bash specific operations (see `checkbashisms` tool)

**Comment by sylv-io** [comment]
Since some of the scripts use bashisms and the whole build environment (make) uses bash as shell, we would stick with bash to keep it simple.
But in general you are right, one should rather use `sh` over `bash`, if possible.
