### ISSUE TITLE
Avoid hardcoded passwords (even hashed/encrypted)

### ISSUE THREAD

**Issue by emanuelb** [system-transparency/system-transparency#62]
https://github.com/system-transparency/system-transparency/blob/c88c2fe59ecc334c5bbd96b89c94500b455f1a0e/operating-system/debian/debos.yaml#L45
https://github.com/system-transparency/system-transparency/blob/95d14b92ad854b5d4bd83fe1b3fe72a6185c2585/operating-system/ubuntu/debos_add_standard_user.sh#L6
Better to supply this information by the user, such as from stdin or environment variable, etc..

**Comment by sylv-io** [comment]
The debos recipes are currently only for demo purpose.
Furthermore the aim is to create an non-interactive build environment.
I changed the structure, so that the password hash is an argument for the recipe.

We could implement a config variable to change it in future :+1:
