### ISSUE TITLE
Enlarge STDATA partition

### ISSUE THREAD

**Issue by jensdrenhaus** [system-transparency/system-transparency#76]
There must be enough space on the STDATA partition for stboot to write a OS package ZIP archive to `stboot/os-pkgs/cache`

**Comment by sylv-io** [comment]
looks like `stboot-installation/common/build_data_filesystem.sh` already calculates the estimated size in line  26 (os-package dir + 100MB).
I tested it by adding a 1GB raw file in `out/os-packages` and it was successfully included. At build-time.

closed for now. It i misunderstood your issue, feel free to reopen it and restate the issue description :grin:

**Comment by jensdrenhaus** [comment]
STDATA needs enough free space to store an additional OS package

**Comment by sylv-io** [comment]
should we implement it as config variable?
in addition i could look into an auto resize hook at runtime.
In this way it should use the complete disk.

**Comment by jensdrenhaus** [comment]
Do you think of a variable defining the extra free space at STDATA partition. Yes I think that's a good idea.
The auto resize hook is a topic for the go code of stboot. Lets's finish this here first. But sure you evaluate solutions for a runtime modification than.

**Comment by sylv-io** [comment]
I'm working on a PR implementing `ST_DATA_PARTITION_EXTRA_SPACE`, as a substitute for `ST_DATA_PARTITION_SZIZE`.
It should define the additional space of the STDATA partition. However, the current calculation does not consider the block structure of the ext4 partition. The PR will fix the calculation and implement the new configuration variable.

**Comment by jensdrenhaus** [comment]
Done in #95
