### ISSUE TITLE
Incomplete dependency checks

### ISSUE THREAD

**Issue by rgdd** [system-transparency/system-transparency#78]
The `make mbr-bootloader-installation` step in README.md fails if these dependencies are not satisified on Ubuntu 18.04:
1. The system must support KVM. 
2. The system must have `libtspi-dev`, `debootstrap`, and `systemd-nspawn` installed.

Problem: these dependencies are not checked by `make check`.

**Comment by sylv-io** [comment]
I will add the missing dependencies to #77. Thanks!

**Comment by sylv-io** [comment]
#77 was merged. :+1:
